/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIUtils_JNIUtils */

#ifndef _Included_JNIUtils_JNIUtils
#define _Included_JNIUtils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIUtils_JNIUtils
 * Method:    getStringFormA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIUtils_JNIUtils_getStringFormA
  (JNIEnv *, jclass);

/*
 * Class:     JNIUtils_JNIUtils
 * Method:    getStringFormB
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIUtils_JNIUtils_getStringFormB
  (JNIEnv *, jclass);

/*
 * Class:     JNIUtils_JNIUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIUtils_JNIUtils_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     JNIUtils_JNIUtils
 * Method:    getStringFormD
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIUtils_JNIUtils_getStringFormD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
